### ISSUE TITLE
requirement file has these files which are giving the following error

### ISSUE THREAD

**Issue by Rajnigoyal88** [ravirajsinh45/Crop_and_weed_detection#19]
cffi @ file:///C:/ci/cffi_1613247308275/work
mkl-random @ file:///C:/ci/mkl_random_1618854593605/work
numpy @ file:///C:/ci/numpy_and_numpy_base_1618497408168/work
Pillow @ file:///C:/ci/pillow_1617386319301/work
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
six @ file:///C:/ci/six_1605205426665/work

Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\ci\\numpy_and_numpy_base_1618497408168\\work'

**Comment by Rohit3085** [comment]
Yeah same issue

**Comment by ravirajsinh45** [comment]
removed unnecessary path
